services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=doraipitto'
      - 'MONGO_INITDB_ROOT_PASSWORD=<change_this>'
      - 'MONGO_INITDB_ROOT_USERNAME=doraipitto'
    ports:
      - '27017'
  app:
    image: 'ghcr.io/shindouj/doraipitto:latest'
    environment:
      - 'DISCORD_TOKEN=<change_this>'
      - 'MONGODB_HOST=mongodb'
      - 'MONGODB_PORT=27017'
      - 'MONGODB_DATABASE=doraipitto'
      - 'MONGODB_USERNAME=doraipitto'
      - 'MONGODB_PASSWORD=<change_this>'