spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:doraipitto}
      username: ${MONGODB_USERNAME:doraipitto}
      password: ${MONGODB_PASSWORD}
      authentication-database: admin